// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: definitions/calculator.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operations int32

const (
	Operations_ADDITION       Operations = 0
	Operations_SUBTRACTION    Operations = 1
	Operations_MULTIPLICATION Operations = 2
	Operations_DIVISION       Operations = 3
)

// Enum value maps for Operations.
var (
	Operations_name = map[int32]string{
		0: "ADDITION",
		1: "SUBTRACTION",
		2: "MULTIPLICATION",
		3: "DIVISION",
	}
	Operations_value = map[string]int32{
		"ADDITION":       0,
		"SUBTRACTION":    1,
		"MULTIPLICATION": 2,
		"DIVISION":       3,
	}
)

func (x Operations) Enum() *Operations {
	p := new(Operations)
	*p = x
	return p
}

func (x Operations) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operations) Descriptor() protoreflect.EnumDescriptor {
	return file_definitions_calculator_proto_enumTypes[0].Descriptor()
}

func (Operations) Type() protoreflect.EnumType {
	return &file_definitions_calculator_proto_enumTypes[0]
}

func (x Operations) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operations.Descriptor instead.
func (Operations) EnumDescriptor() ([]byte, []int) {
	return file_definitions_calculator_proto_rawDescGZIP(), []int{0}
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operand1  int32      `protobuf:"varint,1,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2  int32      `protobuf:"varint,2,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operation Operations `protobuf:"varint,3,opt,name=operation,proto3,enum=Operations" json:"operation,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definitions_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_definitions_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetOperand1() int32 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *Input) GetOperand2() int32 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *Input) GetOperation() Operations {
	if x != nil {
		return x.Operation
	}
	return Operations_ADDITION
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operand1  int32      `protobuf:"varint,1,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2  int32      `protobuf:"varint,2,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operation Operations `protobuf:"varint,3,opt,name=operation,proto3,enum=Operations" json:"operation,omitempty"`
	Result    int64      `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definitions_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_definitions_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetOperand1() int32 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *Output) GetOperand2() int32 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *Output) GetOperation() Operations {
	if x != nil {
		return x.Operation
	}
	return Operations_ADDITION
}

func (x *Output) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_definitions_calculator_proto protoreflect.FileDescriptor

var file_definitions_calculator_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a,
	0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x6e, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x6e, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x32, 0x12,
	0x29, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x06, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64,
	0x31, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x32, 0x12, 0x29, 0x0a,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x2a, 0x4d, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x08, 0x41, 0x44, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x55, 0x42, 0x54, 0x52, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x32,
	0x2c, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a,
	0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x06, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x07, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x03, 0x5a,
	0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_definitions_calculator_proto_rawDescOnce sync.Once
	file_definitions_calculator_proto_rawDescData = file_definitions_calculator_proto_rawDesc
)

func file_definitions_calculator_proto_rawDescGZIP() []byte {
	file_definitions_calculator_proto_rawDescOnce.Do(func() {
		file_definitions_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_definitions_calculator_proto_rawDescData)
	})
	return file_definitions_calculator_proto_rawDescData
}

var file_definitions_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_definitions_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_definitions_calculator_proto_goTypes = []interface{}{
	(Operations)(0), // 0: Operations
	(*Input)(nil),   // 1: Input
	(*Output)(nil),  // 2: Output
}
var file_definitions_calculator_proto_depIdxs = []int32{
	0, // 0: Input.operation:type_name -> Operations
	0, // 1: Output.operation:type_name -> Operations
	1, // 2: Calculator.Calculate:input_type -> Input
	2, // 3: Calculator.Calculate:output_type -> Output
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_definitions_calculator_proto_init() }
func file_definitions_calculator_proto_init() {
	if File_definitions_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_definitions_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definitions_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_definitions_calculator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_definitions_calculator_proto_goTypes,
		DependencyIndexes: file_definitions_calculator_proto_depIdxs,
		EnumInfos:         file_definitions_calculator_proto_enumTypes,
		MessageInfos:      file_definitions_calculator_proto_msgTypes,
	}.Build()
	File_definitions_calculator_proto = out.File
	file_definitions_calculator_proto_rawDesc = nil
	file_definitions_calculator_proto_goTypes = nil
	file_definitions_calculator_proto_depIdxs = nil
}
